#!/usr/bin/env expect

set timeout 1;
set tmux_prefix "";

source "./test/helpers.exp"

exec "tmux kill-session -t test";
spawn tmux -f ./test/conf/custom-patterns.conf new -s test;
sleep 0.5;

init_pane
exec "cat ./test/fixtures/custom-patterns";

send "echo yanked text is "
invoke_fingers;
send "i";
tmux_paste;

invoke_fingers;
send "o";
tmux_paste;

send "\r";
sleep 0.5;

expect {
  "yanked text is W00TW00TW00TYOLOYOLOYOLO" { exit_ok }
  timeout { exit_fail }
}

exit $exit_code;
