#!/usr/bin/env expect

set timeout 1;
set tmux_prefix "";

source "./test/helpers.exp"

exec "tmux kill-session -t test";
exec "rm -rf /tmp/tmux-yank-result"

spawn tmux -f ./test/conf/basic.conf new -s test;
sleep 0.5;

init_pane
tmux_send "%"
tmux_send "%"
tmux_send "%"
tmux_send "z"

exec "cat ./test/fixtures/grep-output";
invoke_fingers;

send ""

exec "echo \"current pane is \$(tmux list-panes -F '#{?window_zoomed_flag,zoomed,not_zoomed}' | head -1)\""

expect {
  "current pane is zoomed" { exit_ok }
  timeout { exit_fail }
}

exit $exit_code;
