name: Deployment

on:
  release:
    types:
      - created

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Update Libs
      run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev yaml-static
    - name: Build
      run: shards build --production --release --static --no-debug
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/tmux-fingers
        asset_name: tmux-fingers-${{ github.event.release.tag_name }}-linux-x86_64
        asset_content_type: binary/octet-stream
  dist_homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: tmux-fingers
          homebrew-tap: morantron/homebrew-tmux-fingers
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
